2018 Preview release

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,25 +1,18 @@
 
 #
-# Copyright (C) 2017 Intel Corporation.
+# Copyright 2018 Intel Corporation.
 # 
-# The Intel(R) Machine Learning Scaling Library ("Software") is furnished under
-# license and may only be used or copied in accordance with the terms of that
-# license. No license, express or implied, by estoppel or otherwise, to any
-# intellectual property rights is granted by this document. The Software is
-# subject to change without notice, and should not be construed as a commitment
-# by Intel Corporation to market, license, sell or support any product or
-# technology. Unless otherwise provided for in the license under which this
-# Software is provided, the Software is provided AS IS, with no warranties of any
-# kind, express or implied. Except as expressly permitted by the Software license,
-# neither Intel Corporation nor its suppliers assumes any responsibility or
-# liability for any errors or inaccuracies that may appear herein. Except as
-# expressly permitted by the Software license, no part of the Software may be
-# reproduced, stored in a retrieval system, transmitted in any form, or
-# distributed by any means without the express written consent of
-# Intel Corporation.
+# This software and the related documents are Intel copyrighted materials, and your use of
+# them is governed by the express license under which they were provided to you (License).
+# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
+# disclose or transmit this software or the related documents without Intel's prior written
+# permission.
+# 
+# This software and the related documents are provided as is, with no express or implied
+# warranties, other than those that are expressly stated in the License.
 #
 ENABLE_DEBUG ?= 1
-
+SHELL = bash
 INCLUDES = -I$(MLSL_ROOT)/intel64/include
 LDFLAGS  = -L$(MLSL_ROOT)/intel64/lib -lmlsl -lrt
 CXX     ?= g++
@@ -52,6 +45,9 @@ run: all
 			for dist_upd in 1 0 ; do \
 				echo "group_count = $$group_count, dist_update = $$dist_upd, user_buf = $$usr_buf, stats = 0" >> output.log 2>&1 ; \
 				mpiexec.hydra -n 4 -ppn 1 -l ./$(tests) $$group_count $$dist_upd $$usr_buf 0 >> output.log 2>&1 ; \
+				if [ "$${PIPESTATUS[0]}" -ne 0 ]; then \
+					echo "Run FAILED." ; \
+				fi ; \
 			done ; \
 		done ; \
 	done ;
@@ -59,6 +55,9 @@ run: all
 		echo "running mlsl_test with quantization ..." ; \
 		echo "group_count = 1, dist_update = 0, user_buf = 0, stats = 0" >> output_with_quant.log 2>&1 ; \
 		mpiexec.hydra -n 4 -ppn 1 -l ./$(tests) 1 0 0 0 $(PATH_TO_QUANT_LIB) >> output_with_quant.log 2>&1 ; \
+		if [ "$${PIPESTATUS[0]}" -ne 0 ]; then \
+			echo "Run FAILED." ; \
+		fi ; \
 	fi ;
 	echo "running mlsl_test.py ..." ; \
 	for group_count in 1 2 4 ; do \
@@ -66,6 +65,9 @@ run: all
 			for dist_upd in 1 0 ; do \
 				echo "group_count = $$group_count, dist_update = $$dist_upd, user_buf = $$usr_buf, stats = 0" >> output_py.log 2>&1 ; \
 				mpiexec.hydra -n 4 -ppn 1 -l python ./$(tests).py $$group_count $$dist_upd $$usr_buf 0 >> output_py.log 2>&1 ; \
+				if [ "$${PIPESTATUS[0]}" -ne 0 ]; then \
+					echo "Run FAILED." ; \
+				fi ; \
 			done ; \
 		done ; \
 	done ;
